### ISSUE TITLE
thread 'main' panicked at 'unshare failed: Sys(EPERM)', src/libcore/result.rs:997:5

### ISSUE THREAD

**Issue by fcying** [nix-community/nix-user-chroot#10]
I run the release binary,  it get a error
```
$wget https://github.com/nix-community/nix-user-chroot/releases/download/1.0.2/nix-user-chroot-bin-1.0.2-x86_64-unknown-linux-musl
$ chmod +x nix-user-chroot-bin-1.0.2-x86_64-unknown-linux-musl
$ RUST_BACKTRACE=1 ./nix-user-chroot-bin-1.0.2-x86_64-unknown-linux-musl ~/.nix bash -c "curl https://nixos.org/nix/install | bash"
thread 'main' panicked at 'unshare failed: Sys(EPERM)', src/libcore/result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
thread 'main' panicked at 'failed to remove temporary directory: /tmp/nix.LLZ3Yi9mahOD', src/main.rs:200:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
```

**Comment by zimbatm** [comment]
It looks like your user is not allowed to call `unshare`, this is quite common on old CentOS and RedHat kernels.

**Comment by zimbatm** [comment]
If that's the case there is not much we can do unfortunately.

**Comment by fcying** [comment]
os: debian10
How do you turn this feature on debian 10?
```
$ grep CONFIG_USER_NS /boot/config-$(uname -r)
CONFIG_USER_NS=y
```
```
$unshare --user --pid echo YES
unshare: unshare failed: Operation not permitted
```

**Comment by zimbatm** [comment]
no problem

**Comment by deb947** [comment]
I'm facing the same problem, but not on a CentOS/RedHat, this is Debian. Also, the output for the command:
`grep CONFIG_USER_NS /boot/config-$(uname -r)` 
is:
`CONFIG_USER_NS=y`

**Comment by Mic92** [comment]
@deb947 I think debian also had an option to disable usernamespaces at runtime even if it is supported in the kernel itself.

**Comment by mfouesneau** [comment]
All tickets are closed, I cannot find the solution.  I managed to use it and this error started.
