### ISSUE TITLE
nix-user-chroot crashes at startup

### ISSUE THREAD

**Issue by valmar** [nix-community/nix-user-chroot#5]
When I try to use nix-user-chroot to install nix without root permissions, it crashed with the following error:

```
$ RUST_BACKTRACE=1 ./nix-user-chroot ~/.nix bash -c "curl https://nixos.org/nix/install | bash"
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', src/main.rs:117:44
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
```

I tried both the pre-built binaries and building from source

Thank you for any help you can provide!

**Comment by Mic92** [comment]
Ok. So the actual problem is that your command is failing and while printing the error message, it crashes: https://github.com/nix-community/nix-user-chroot/blob/80216394fa45a7da2432e4587500f8d446752590/src/main.rs#L113

**Comment by Mic92** [comment]
Does the error still persist in current master?

**Comment by Mic92** [comment]
Here is a proper fix: https://github.com/nix-community/nix-user-chroot/pull/6

**Comment by valmar** [comment]
Uhm... I just built from master. It still crashes but now we have a proper stacktrace

I have to say that I am running this on RH7.4 from my workplace. I read this in the documentaiton:

> On RedHat / CentOS 7.4 user namespaces are disabled by default, but can be enabled by:

I don't have control over the boot parameters, so I can not enable the namespaces myself. However, it looks like they are already enabled:

```
unshare --user --pid echo YES
YES
```

Thank you so much for your help! Here is the stacktrace:

```
RUST_BACKTRACE=1 ./nix-user-chroot ~/.nix bash
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 2', src/main.rs:151:44
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   9: nix_user_chroot::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: main
```

**Comment by valmar** [comment]
Using the fix-oob branch the program runs, but the installation fails:

```
./nix-user-chroot ~/.nix bash -c "curl https://nixos.org/nix/install | bash" 
failed to execute bash: No such file or directory (os error 2)
```
Thanks for all your help!

**Comment by Mic92** [comment]
Yeah. But this is a different problem then.

**Comment by valmar** [comment]
Ok I will open another issue! Thanks!

**Comment by Mic92** [comment]
Well, you need to have bash installed. Do you?
